# Generated by Django 2.2.3 on 2019-08-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='users_joining',
        ),
        migrations.AddField(
            model_name='trip',
            name='users_trips',
            field=models.ManyToManyField(related_name='other_travel_plans', to='myapp.User'),
        ),
    ]
